Add Sustainbench Crop Yield Dataset
microsoft/torchgeo pull request #1253
Opened 2023-04-17 14:30 UTC by nilsleh

This PR adds the [Sustainbench Crop Yield Dataset](https://sustainlab-group.github.io/sustainbench/docs/datasets/sdg2/crop_yield.html) as a dataset with a corresponding dataloader.

Dataset Format:
- .npz file of stacked samples

Dataset Features:
- MODIS band histograms across time with regression target of soybean yield in metric tonnes

Questions:
- the dataloading from the .nzp files seems quiet slow, as it always has to index the .npz files but I am not sure how to speed it up

Example:
<img src="https://user-images.githubusercontent.com/35272119/232516865-1d8160bc-f9f5-4e83-ad88-05d9555178de.png" align="center" height="400" width="400" >

2023-04-17 15:54 UTC, adamjstewart commented on torchgeo/datamodules/sustainbench_crop_yield_prediction.py
> +        .. versionadded:: 0.5
This should be in the class docstring. It's not just `__init__` that was added, it's the entire class

2023-04-19 16:36 UTC, adamjstewart requested changes
Lots of inconsistencies in naming. Need to decide between SustainBenchCropYield and SustainBenchCropYieldPrediction (I prefer the former because it's shorter). Also it should be SustainBench, not Sustainbench.

2023-04-19 16:36 UTC, adamjstewart commented on docs/api/datamodules.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
SustainBench Crop Yield
^^^^^^^^^^^^^^^^^^^^^^^
```

2023-04-19 16:36 UTC, adamjstewart commented on torchgeo/datamodules/sustainbench_crop_yield_prediction.py
> +        state here is recommended.
I usually drop this paragraph from datamodules because it's documented in the base class.

2023-04-19 16:36 UTC, adamjstewart commented on torchgeo/datasets/sustainbench_crop_yield_prediction.py
Would it make sense to add all SustainBench datasets to a single file, or should they be in separate files?

2023-04-19 16:59 UTC, nilsleh commented on torchgeo/datasets/sustainbench_crop_yield_prediction.py
Not sure, there are 15 SustainBench datasets in total so one file would probably grow very large?

2023-04-19 17:36 UTC, adamjstewart commented on torchgeo/datasets/sustainbench_crop_yield_prediction.py
I guess it depends on if they follow a consistent file format like SpaceNet or not. If they can't share a base class, then there's no reason to group them

2023-04-19 17:38 UTC, adamjstewart reviewed
Still a bunch of directories and filenames containing "prediction"

2023-04-19 17:47 UTC, nilsleh commented on torchgeo/datasets/sustainbench_crop_yield_prediction.py
the tasks are all different (some have overlap) but they cover segmentation, classification, regression, ... https://sustainlab-group.github.io/sustainbench/about/

2023-04-19 19:11 UTC, adamjstewart commented on torchgeo/datamodules/sustainbench_crop_yield.py
> +        """Initialize a new DataModule instance.
```suggestion
        """Initialize a new SustainBenchCropYieldDataModule instance.
```

2023-04-19 19:11 UTC, adamjstewart commented on torchgeo/datamodules/sustainbench_crop_yield.py
> +            self.train_dataset = self.dataset_class(  # type: ignore[call-arg]
Let's use `SustainBenchCropYield` here to avoid the type ignore

2023-04-19 19:11 UTC, adamjstewart commented on torchgeo/datasets/sustainbench_crop_yield.py
> +            FileNotFoundError: if no files are found in ``root``
Never raised

2023-04-19 19:11 UTC, adamjstewart commented on torchgeo/datasets/sustainbench_crop_yield.py
> +            AssertionError: if ``countries`` contains invalid countries
Or if split is invalid

2023-04-19 19:31 UTC, adamjstewart submitted a review, later dismissed

2023-04-20 15:11 UTC, merged