add gassl weights
microsoft/torchgeo pull request #1325
Opened 2023-05-11 22:04 UTC by isaaccorley

This PR adds the ResNet50 RGB weights trained on fMoW (mostly Maxar WorldView imagery) using the  [Geography Aware Self-supervised Learning (GASSL)](https://arxiv.org/abs/2011.09980) method. This is basically a modified MoCo-v2 with Geolocation as a pretext task (Geo) as well as temporal pairs contrastive learning (TP).

Weights taken from [this repo](https://github.com/sustainlab-group/geography-aware-ssl) and uploaded to huggingface.

Adding these weights is essential since it's being compared as a baseline in both the [SatMAE](https://arxiv.org/abs/2207.08051) and [Scale-MAE](https://arxiv.org/abs/2212.14532) papers.

2023-05-12 04:11 UTC, adamjstewart requested changes
Need to add to `docs/api/resnet_pretrained_weights.csv`. We should start thinking about how we want to handle multiple satellites. I'm thinking we'll want different tables for each satellite since the benchmark datasets will differ. We can punt that to the PR where we add all our new SSL4EO-L models.

2023-05-12 04:11 UTC, adamjstewart commented on torchgeo/models/resnet.py
> +        url="https://huggingface.co/torchgeo/resnet50_fmow_rgb_gassl/resolve/main/resnet50_fmow_rgb_gassl-44b4461b.pth",  # noqa: E501
This is the MD5 checksum. torch.hub.download_url uses the SHA256 checksum. Can you change it to da43d987? You'll also need to rename the file on HF.

2023-05-12 04:11 UTC, adamjstewart commented on torchgeo/models/resnet.py
> +    FMOW_RGB_GASSL = Weights(
I would put this first since it comes first alphabetically

2023-05-12 19:52 UTC, isaaccorley commented
Should I add the transforms as well? They only train on the fmow RGB data which is uint8 and they just divide by 255 and use imagenet normalization.

2023-05-12 22:39 UTC, isaaccorley commented
No idea why coverage is failing

2023-05-23 23:16 UTC, calebrob6 commented
This LGTM, @adamjstewart any problems with merging this?

2023-05-23 23:18 UTC, adamjstewart commented
Give me some time to review. How urgent is this? Would prefer to focus on the paper until the deadline, but can review sooner if needed. I mostly want to verify the transforms and filename and such.

2023-05-24 03:36 UTC, calebrob6 commented
I've checked the sha256sum and transforms so I think we're good
![image](https://github.com/microsoft/torchgeo/assets/1088078/5588f2bd-07fc-4233-bc5c-76fa7c675bed)

![image](https://github.com/microsoft/torchgeo/assets/1088078/94e65a07-99dd-464b-809e-87c0376746f6)

2023-05-24 03:58 UTC, adamjstewart commented
Do we want to call it fMoW or Maxar? Might be more clear what the weights can be used for with the latter.

2023-05-24 04:10 UTC, calebrob6 commented
The current name fits with the existing scheme `{model}_{dataset}_{bands}_{paper/source}_{hash}` -- regardless, users aren't interacting with the actual file.

2023-05-24 04:22 UTC, calebrob6 approved these changes

2023-05-24 13:54 UTC, isaaccorley commented
Fmow RGB is more than just Maxar though.

2023-05-24 14:53 UTC, adamjstewart approved these changes

2023-05-24 14:54 UTC, adamjstewart commented
Why did you choose Apache 2.0 for the license?

2023-05-24 15:20 UTC, calebrob6 commented
Where are you seeing "Apache 2.0"?

2023-05-24 15:41 UTC, calebrob6 commented
It seems the weights aren't licensed -- but just to be clear, we are _not_ uploading the weights to this repo. It is always good to ask the authors though.

2023-05-24 15:42 UTC, merged

2023-05-24 16:18 UTC, isaaccorley commented
I'll change the license on HF

2023-05-24 16:31 UTC, calebrob6 commented
Already did