Add year filter functionality CDL
microsoft/torchgeo pull request #1337
Opened 2023-05-15 10:28 UTC by nilsleh

This PR adds `years` argument to select a number of years for which to download CDL or use CDL so the user doesn't have to download all 15 years. This is how we decided to implement it for NLCD as well.

2023-05-15 15:12 UTC, adamjstewart requested changes
Needs more coverage

2023-05-15 15:12 UTC, adamjstewart commented on torchgeo/datasets/cdl.py
> +        years: list[int] = [2019],
If we're going to default to something let's default to the most recent year

2023-05-15 15:32 UTC, nilsleh commented on torchgeo/datasets/cdl.py
> +            pathname = os.path.join(self.root, filename_year)
The implementation here, is how it is currently done for `nlcd.py`.

2023-05-20 16:47 UTC, adamjstewart requested changes

2023-05-20 16:47 UTC, adamjstewart commented on torchgeo/datasets/cdl.py
> +            Added *years* parameter
```suggestion
        .. versionadded:: 0.5
           The *years* parameter.
```

2023-05-20 16:47 UTC, adamjstewart commented on torchgeo/datasets/cdl.py
> +                exists.append(False)
```suggestion
            exists.append(os.path.exists(pathname))
```

2023-05-20 16:47 UTC, adamjstewart commented on torchgeo/datasets/cdl.py
> +                self.root, filename_year.removesuffix(".tif"), filename_year
We should keep the recursive glob so that people can specify a higher or lower root directory (e.g., `root=/path/to/2019_30m_cdls/` or `root=/path/`)

2023-05-25 03:15 UTC, adamjstewart approved these changes
Remaining issues are very trivial. Feel free to merge this if you want to focus on different things.

2023-05-25 03:15 UTC, adamjstewart commented on torchgeo/datasets/cdl.py
>          # Check if the extracted files already exist
This is **very** unimportant but I wonder if we should instead have a single for-loop over all versions and only download/extract the exact versions we need to. Imagine a situation where someone downloaded and extracted 2021, but then 2022 came out and they wanted to use that too. At the moment, Spack would try to re-download (torchvision will skip this for us) and re-extract the zip file for 2021 even though it's already extracted.

2023-05-25 03:15 UTC, adamjstewart commented on torchgeo/datasets/cdl.py
>      is_image = False
I think the glob/regex will still pick up versions other than the ones requested if they are found on the system. You _could_ fix this by editing the `filename_regex` during `__init__`. We do something similar to this in our Landsat datasets where we patch `filename_glob` based on the bands requested.

2023-05-25 06:25 UTC, merged