add Satlas pretrained models
microsoft/torchgeo pull request #1358
Opened 2023-05-23 17:01 UTC by isaaccorley

Adds Swin Transformer v2 Base pretrained models from the [Satlas](https://github.com/allenai/satlas) dataset

2023-05-23 17:09 UTC, adamjstewart commented
Will review after deadline

2023-05-23 23:17 UTC, calebrob6 commented
is the `timm` swin transformer compatible?

2023-05-23 23:38 UTC, isaaccorley commented
No it's not. The layers are named differently unfortunately.

2023-05-23 23:38 UTC, isaaccorley commented
Wonder if I can map them to each other.

2023-05-24 00:55 UTC, adamjstewart commented
If it's not to hard, that would be useful since it would let us use it in our trainers. Wonder if we could add some kind of logic to support both timm and torchvision in our trainers...

2023-05-24 01:31 UTC, isaaccorley commented
It is hard unfortunately.

2023-06-20 23:51 UTC, calebrob6 approved these changes

2023-11-19 23:43 UTC, isaaccorley commented
I have no idea why the figure plotting in `torchgeo/trainers/detection.py` is somehow indirectly not covered via codecov

2023-11-20 09:29 UTC, adamjstewart requested changes

2023-11-20 09:29 UTC, adamjstewart commented on requirements/min-reqs.old
Also need to update `pyproject.toml`

2023-11-20 09:29 UTC, adamjstewart commented on torchgeo/models/swin.py
> +from torchvision.models.swin_transformer import SwinTransformer
```suggestion
from torchvision.models import SwinTransformer
```
The sub-sub-modules aren't really public.

2023-11-20 09:29 UTC, adamjstewart commented on torchgeo/models/swin.py
> +# All Satlas imagery is uint8 and normalized to the range (0, 1) by dividing by 255 # noqa: E501
This doesn't need noqa, you can just wrap the line

2023-11-20 22:44 UTC, adamjstewart commented
Turns out the decrease in test coverage is actually very important!

If you remove the try-except from ObjectDetectionTask, you'll find that there is a bug in our implementation:
```
FAILED tests/trainers/test_detection.py::TestObjectDetectionTask::test_trainer[True-faster-rcnn-nasa_marine_debris] - ValueError: Boxes need to be in (xmin, ymin, xmax, ymax) format. Use torchvision.ops.box_convert to convert them
FAILED tests/trainers/test_detection.py::TestObjectDetectionTask::test_trainer[True-fcos-nasa_marine_debris] - ValueError: Boxes need to be in (xmin, ymin, xmax, ymax) format. Use torchvision.ops.box_convert to convert them
FAILED tests/trainers/test_detection.py::TestObjectDetectionTask::test_trainer[True-retinanet-nasa_marine_debris] - ValueError: Boxes need to be in (xmin, ymin, xmax, ymax) format. Use torchvision.ops.box_convert to convert them
FAILED tests/trainers/test_detection.py::TestObjectDetectionTask::test_no_rgb[True] - ValueError
```
These were being masked by our try-except. The code works fine for torchvision 0.13 but breaks for any newer version. We didn't notice this because the combined coverage didn't change. From what I can tell, this has always been broken...

2023-11-20 22:45 UTC, adamjstewart commented
Can you try to fix that in a separate PR so we can backport it to 0.5.2? Or one of us can do it, just let me know if you're busy.

2023-11-20 23:11 UTC, isaaccorley commented
> Can you try to fix that in a separate PR so we can backport it to 0.5.2? Or one of us can do it, just let me know if you're busy.

I'll push a PR here shortly

2023-11-21 08:55 UTC, adamjstewart approved these changes
Can merge as soon as coverage issue is fixed.

2023-11-25 20:12 UTC, adamjstewart commented on docs/api/misc_pretrained_weights.csv
> +Swin_V2_B_Weights.SENTINEL2_RGB_SATLAS,3,`link <https://github.com/allenai/satlas>`__,`link <https://arxiv.org/abs/2211.15660>`__
If we know what satellite they were trained on, these should have their own categories/files. So Sen 2 should go under Sen 2, and we should have a new category/file for NAIP.

2023-11-25 20:30 UTC, adamjstewart approved these changes

2023-11-25 20:39 UTC, merged