Added the UC Merced dataset
microsoft/torchgeo pull request #169
Opened 2021-09-26 09:36 UTC by calebrob6

2021-09-26 21:41 UTC, isaaccorley commented
I don't think you need rasterio to load the images since they are already uint8 tiffs iirc. You could basically copy paste the PatternNet and RESISC45 datasets and just change the docstring and file metadata.

This came up in another PR, but we should probably create some VisionClassification class which can be subclassed with minimal changes for generic classification datasets with images split into separate directories for each class.

2021-09-26 21:46 UTC, calebrob6 commented
Oh cool, yeah that's a better way -- will change

2021-09-27 20:41 UTC, adamjstewart requested changes

2021-09-27 20:41 UTC, adamjstewart commented on torchgeo/datasets/ucmerced.py
> +    @lru_cache()
No reason to cache this, the cache will almost never be hit since it only keeps the 128 most recent images and the dataset size is 2.1K.

2021-09-27 20:41 UTC, adamjstewart commented on torchgeo/datasets/ucmerced.py
> +            with rasterio.open(filename) as f:
I agree with @isaaccorley, we should just use Pillow if this isn't a GeoTIFF

2021-09-28 01:13 UTC, adamjstewart approved these changes

2021-09-28 01:14 UTC, merged